[book]
authors = ["Cardinal Cryptography"]
language = "en"
description = "Documentation of the rust implementation of Aleph protocol"
multilingual = false
src = "docs/src"
title = "Rush - Aleph in Rust"

[build]
build-dir = "docs/book"
create-missing = false
